# Generated by Django 4.1.1 on 2022-09-21 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='name',
            new_name='tittle',
        ),
        migrations.AddField(
            model_name='tasks',
            name='userId',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tarefas.users'),
        ),
    ]
