# Generated by Django 4.1.1 on 2022-09-21 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_users_rename_name_tasks_tittle_tasks_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='tittle',
            new_name='title',
        ),
    ]
